# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 13:27
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kidfolio', '0002_auto_20171218_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=34)),
            ],
        ),
        migrations.CreateModel(
            name='KidPicPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, storage=django.core.files.storage.FileSystemStorage(location='/kidfolio/static/images/'), upload_to='', width_field='width_field')),
                ('height_field', models.IntegerField(default=400)),
                ('width_field', models.IntegerField(default=400)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=34)),
                ('caption', models.TextField(blank=True, max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(max_length=34)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='kidfolio.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='Kidpic',
        ),
        migrations.AddField(
            model_name='kidpicpost',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidfolio.Portfolio'),
        ),
    ]
