# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kidfolio', '0003_auto_20171219_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='category',
        ),
        migrations.AddField(
            model_name='kidpicpost',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kidfolio.Category'),
            preserve_default=False,
        ),
    ]
