# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidfolio', '0004_auto_20171219_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kidpicpost',
            name='category',
        ),
        migrations.AddField(
            model_name='kidpicpost',
            name='category',
            field=models.ManyToManyField(to='kidfolio.Category'),
        ),
    ]
